# Generated by Django 5.0.4 on 2024-05-05 20:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
