# Generated by Django 5.0.4 on 2024-05-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_files', to='files.category'),
        ),
    ]
