# Generated by Django 5.0.4 on 2024-05-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_file_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ManyToManyField(to='files.category'),
        ),
    ]
