# Generated by Django 5.0.4 on 2024-05-06 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_remove_file_category_file_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file_category', to='files.category'),
            preserve_default=False,
        ),
    ]
