# Generated by Django 5.0.4 on 2024-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_remove_file_category_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.IntegerField(),
        ),
    ]
