# Generated by Django 5.0.4 on 2024-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_alter_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
