# Generated by Django 5.0.4 on 2024-05-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_alter_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='name_file',
        ),
    ]
